### PR TITLE
Add Splash Screen image

### PR DESCRIPTION
**Pull request by cibersheep**

### CODE REVIEW

**Comment by cibersheep** [comment]
SplashScreen Before / After

imatge

imatge

**Review by dobey — APPROVED** [review]
Looks good.

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-40.
It works.
Thanks @cibersheep !!!

**Comment by TellingBerto** [comment]
Device: VollaPhone
Channel: rc
Build: 2020-W43

Result: Splash screen is displayed.

**Pull request merged**
